### PR TITLE
Begin adding e2e tests

### PR DESCRIPTION
**Pull request by trevormunoz**
Without sinking too much time into testing, I think we can benefit from having at least a small test suite to check that pages are the way we want as we are remodeling the site.

I've added a super basic set of Playwright tests aimed at the top-level pages to start.

You can use `npm run test` to launch the tests.

### CODE REVIEW

**Comment by trevormunoz** [comment]
I purposefully included a failing test to start: https://github.com/umd-mith/mith-static/blob/a2a33f82acb95d78553d8e27ca731ee51aebd81d/tests/top-level-pages.spec.ts#L31C1-L36C3

Also, see the note about "invisible" elements (relevant to current People page design): https://github.com/umd-mith/mith-static/blob/a2a33f82acb95d78553d8e27ca731ee51aebd81d/tests/top-level-pages.spec.ts#L21C3-L28C46

**Comment by trevormunoz** [comment]
Once we go this route, we can also add workflow steps to run tests before building the staging site

**Review by raffazizzi — APPROVED** [review]
@trevormunoz I had to increased the timeout time for this to work on my machine. Processing the nodes from Airtable can take a while... I'm looking at a strategy to cache them better, but we'll still need a generous timeout in case the tests are run before a first build.

I also needed to install playwright as a binary with `npx playwright install`, a step that will be needed in the deployment workflow(s) as well.

Otherwise, it behaves as expected, returning the error for title and h1 on the news page. I think we can merge this and keep working on it on the main branch,

**Comment by trevormunoz** [comment]
@raffazizzi Were you running into these errors with the Gatsby build on Actions? https://github.com/umd-mith/mith-static/actions/runs/9998232860/job/27636795516#step:6:22

(I think this is a Gatsby timeout and not a Playwright one?)

**Comment by raffazizzi** [comment]
That's the same error I was getting when I first tested this branch. `config.webServer` is definitely from Playwright. I thought I increased the timeout to 100000 and that made it got away...

**Comment by trevormunoz** [comment]
> That's the same error I was getting when I first tested this branch. `config.webServer` is definitely from Playwright. I thought I increased the timeout to 100000 and that made it got away...

Weird. Your commit increasing the timeout is definitely there on the branch … lemme look some more

**Comment by trevormunoz** [comment]
So, the timeout needs to be increased in `webServer` stanza of the Playwright config (not just the top level — which is about test timeouts without reference to the Gatsby server startup): https://github.com/umd-mith/mith-static/pull/20/commits/956da36014c5e1c5b0a02c4ec3b3aa8816247cbb#diff-f679bf1e58e8dddfc6cff0fa37c8e755c8d2cfc9e6b5dc5520a5800beba59a92R79

See https://playwright.dev/docs/test-webserver#configuring-a-web-server

We need the increased timeout to wait for the Gatsby startup (as you said).

Now the Actions test results match the local ones

**Pull request merged**
